apiVersion: v1
kind: Service
metadata:
  name: simple-webserver
spec:
  type: NodePort
  selector:
    app: simple-webserver
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 80
