apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webserver
spec:
  selector:
    matchLabels:
      app: simple-webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-webserver
    spec:
      containers:
        - name: simple-webserver
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
